jobs:
  - name: clear-dynamodb-row-development
    plan:
      - .: (( inject meta.plan.clear-dynamodb-row ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            AWS_ACC: ((aws_account.development))
            CORRELATION_ID: ingest_emr_scheduled_tasks_export_snapshots_to_crown_development_incremental_157_incremental
            DATA_PRODUCT: MONGO_LATEST
