jobs:
  - name: prod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            CORRELATION_ID: a7bda2f0-13f9-5fdf-98b0-fba47b91d55e
            EXPORT_DATE: "2021-06-29"
