jobs:
  - name: prod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
            AWS_ACC: ((aws_account.production))
            CORRELATION_ID: 071c488d-e920-50dc-b5f6-11c2cb489d9f
            EXPORT_DATE: "2021-06-25"
