jobs:
  - name: dev-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
            AWS_ACC: ((aws_account.development))
            CORRELATION_ID: test
            EXPORT_DATE: "2020-08-13"
