jobs:
  - name: preprod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            CORRELATION_ID: 0162c1e6-3a9e-5831-8e61-98cc02f06fb1
            EXPORT_DATE: "2021-05-28"
