jobs:
  - name: preprod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            CORRELATION_ID: 95f2519f-fb92-52f1-be85-08d22b7c43fb
            EXPORT_DATE: "2021-06-24"
