jobs:
  - name: preprod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            CORRELATION_ID: ad107e42-e5f1-5275-b16c-2709c81fc6b2
            EXPORT_DATE: "2021-06-22"
