jobs:
  - name: preprod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            CORRELATION_ID: 3e3a08b7-6339-5725-a5e6-518fdbd738ad
            EXPORT_DATE: "2021-06-08"
