jobs:
  - name: preprod-start-cluster
    plan:
      - .: (( inject meta.plan.start-cluster ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            S3_PREFIX: analytical-dataset/full/2021-05-06_01-44-46/
            CORRELATION_ID: test
            SNAPSHOT_TYPE: "full"
            EXPORT_DATE: "2021-05-06"
