jobs:
  - name: aws-mongo-latest-preprod
    max_in_flight: 1
    plan:
      - in_parallel:
          - get: dataworks-aws-mongo-latest
            trigger: true
            passed:
              - aws-mongo-latest-qa
          - get: al2-emr-ami
            trigger: true
            passed:
              - aws-mongo-latest-qa
          - get: emr-launcher-release
            version: { tag: ((emr-launcher-version.preprod)) }
            trigger: true
            passed:
              - aws-mongo-latest-qa
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.preprod)) }
            trigger: true
            passed:
              - aws-mongo-latest-qa
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: preprod
