jobs:
  - name: dev-branch-in-dev
    plan:
      - get: dataworks-aws-mongo-latest
        resource: dataworks-aws-mongo-latest-pipeline
        trigger: true
      - task: aviator
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.docker_aviator_repository))
              version: ((dataworks.docker_aviator_version))
          run:
            path: sh
            args:
              - -exc
              - |
                sed '1,/".*yml"/s//"^(?!.*dev).*yml"/' aviator.yml
                sed '/aviator_pipeline.*/i     \      - with_in: ci/jobs/dev-branch-dev\n        regexp: ".*yml"' aviator.yml
                cat ci/resources.yml| grep -B 1 -A 7 -E ": dataworks-aws-mongo-latest$"| sed '/latest$/ s/$/-dev/' | sed 's/branch:.*/branch: dev/' >>ci/resources.yml
                sed -i 's/fly/nofly/' aviator.yml
                /usr/bin/aviator -f aviator.yml
                mv aviator_pipeline.yml ../pipeline
                mv ci/vars.yml ../pipeline
            dir: dataworks-aws-mongo-latest
          inputs:
            - name: dataworks-aws-mongo-latest
          outputs:
            - name: pipeline
      # - set_pipeline: aws-mongo-latest
      #   file: pipeline/aviator_pipeline.yml
      #   var_files:
      #     - pipeline/vars.yml
