jobs:
  - name: development
    max_in_flight: 1
    plan:
      - get: aws-emr-template-repository
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
      - .: (( inject meta.plan.terraform-plan ))
