jobs:
  - name: aws-mongo-latest-qa
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-qa
          - get: dataworks-aws-mongo-latest
            trigger: true
          - get: emr-launcher-release
            trigger: true
          - get: dataworks-behavioural-framework
            trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.qa))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: qa
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: qa
      # - .: (( inject meta.plan.e2e-tests))
      #   config:
      #     params:
      #       TF_WORKSPACE: qa
      #       AWS_ACC: ((aws_account.qa))
      #       AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
