jobs:
  - name: clear-dynamodb-row-preprod
    plan:
      - .: (( inject meta.plan.clear-dynamodb-row ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
            AWS_ACC: ((aws_account.preprod))
            CORRELATION_ID: f0e3e7c2-701f-5376-a0a1-be9166f190b0
            DATA_PRODUCT: MONGO_LATEST
